db_name = 'subway'
collisions_path = '/Users/willdecesare/Documents/GitHub/subway-safe/Collisions_20250205.csv'
felonies_path = '/Users/willdecesare/Documents/GitHub/subway-safe/MTAMajorFelonies_20250210.csv'
ridership_path = '/Users/willdecesare/Documents/GitHub/subway-safe/MTADailyRidership_20250210.csv'
nyct_collisions_path = '/Users/willdecesare/Documents/GitHub/subway-safe/MTANYCTSafetyData_20250211.csv'